config/routes.rb
Rails.application.routes.draw do

  resources :applications

  devise_for :users

  root to: "welcome#index"

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy

  validates :name, presence: true, uniqueness: { message: "\"%{value}\" is already in use." }
  validates :url, presence: true, uniqueness: { message: "\"%{value}\" is already in use." }
  validates :user, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :application
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :applications, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    application = Application.find_by(url: request.env['HTTP_ORIGIN'])
    if application == nil
      render json: "ERROR: Unregistered application\n", status: :unprocessable_entity
    else
      @event = Event.new(event_params)
      @event.application = application

      if @event.save
        render json: @event, status: :created
      else
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
    end
  end

  def preflight
    head 200
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :authorize_user, except: [:new, :create, :index]

  def index
    @applications = Application.where(user_id: current_user.id)
  end

  def show
    @application = Application.find(params[:id])
    @event_collection = Event.where(application_id: @application.id)
    @events = Event.where(application_id: @application.id).group_by(&:name)
  end

  def new
    @application = Application.new
  end

  def edit
    @application = Application.find(params[:id])
  end

  def create
    @application = Application.new(application_params)
    @application.user_id = current_user.id

    if @application.save
      redirect_to @application, notice: "Application was added successfully"
    else
      flash.now[:alert] = "Error creating application, try again."
      render :new
    end
  end

  def destroy
    @application = Application.find(params[:id])

    if @application.destroy
      flash[:notice] = "\"#{@application.name}\" was deleted successfully."
      redirect_to applications_path
    else
      flash.now[:alert] = "There was an error deleting the application."
      render :show
    end
  end

  def update
    @application = Application.find(params[:id])
    @application.assign_attributes(application_params)

    if @application.save
      flash[:notice] = "Application was updated."
      redirect_to @application
    else
      flash.now[:alert] = "There was an error saving the application. Please try again."
      render :edit
    end
  end

  private
  def application_params
    params.require(:application).permit(:name, :url)
  end

  def authorize_user
    application = Application.find(params[:id])
    unless current_user == application.user
      flash[:alert] = "You don't have permission to view this application."
      redirect_to applications_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?

    content_tag :div, capture(&block), class: css_class
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/_form.html.erb
<%= form_for application do |f| %>
  <% if application.errors.any? %>
    <div class="alert alert-danger">
      <!-- <h4><%= pluralize(application.errors.count, "error") %>.</h4> -->
      <ul>
        <% application.errors.full_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(application.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
  <% end %>
  <%= form_group_tag(application.errors[:url]) do %>
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Enter application URL" %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Edit</h1>

<%= render partial: 'form', locals: { application: @application } %>

app/views/applications/index.html.erb
<h2>Applications</h2>

<div class="row">
  <div class="col-md-8">
    <% @applications.each do |application| %>
      <div class="media">
        <div class="media-body">
          <h5 class="media-heading"><%= link_to application.name, application %></h4>
          <small><%= application.url %></small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Application", new_application_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/applications/new.html.erb
<h1>New application</h1>

<div class="row">
  <div class="col-md-8">
    <%= render partial: 'form', locals: { application: @application } %>
  </div>
</div>

app/views/applications/show.html.erb
<div class="row">
  <div class="col-md-5">
    <h1>
      <%= @application.name %>
      <small>
        <%= link_to "", edit_application_path, class: 'fa fa-edit no-decor' %>
        <%= link_to "", @application, method: :delete, class: 'fa fa-trash no-decor', data: { confirm: 'Are you sure you want to delete this application?' } %>
      </small>
    </h1>
    <p class="lead">URL: <%= @application.url %></p>
    <p>EVENTS:</p>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">
            Event name
          </th>
          <th scope="col">
            # of events
          </th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |ev| %>
        <tr>
          <td>
            <%= ev[0] %>
          </td>
          <td>
            <%= ev[1].length %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-7">
    <div class="card text-center">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link active" href="#">Event Breakdown</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Timeline</a>
          </li>
        </ul>
      </div>
      <div class="card-body">
        <%= pie_chart @application.events.group(:name).count %>
        <%= line_chart @application.events.group_by_day(:created_at).count %>
      </div>
    </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navtoggle" aria-controls="navtoggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navtoggle">
        <!-- <a class="navbar-brand" href="#">Hidden brand</a> -->
        <%= link_to "Home", root_path, :class => 'navbar-brand' %>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <% if user_signed_in? %>
              <%= link_to "Applications", applications_path, :class => 'nav-link' %>
            <% end %>
          </li>
        </ul>
        <ul class="navbar-nav my-2 my-lg-0">
          <% if user_signed_in? %>
          <li class="nav-item">
            <span class="navbar-text">Signed in as: <strong><%= current_user.email %></strong> | </span>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
          </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, :class => 'nav-link'  %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>

  <div class="container">
    <%= yield %>
    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
    <% end %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<container>
  <h2>
    Wawa-Metrics<br />
    <small class="text-muted">An easy-to-use web analytics service.</small>
  </h2>
  <p>
    Add the following snippet to your application's Javascript file (ie application.js)

    <pre>
      <code>
        var wawametrics = {};

        wawametrics.report = function(eventName) {
          var event = { event: { name: eventName } };
          var request = new XMLHttpRequest();
          request.open("POST", "http://dry-brook-78331.herokuapp.com/api/events", true);
          request.setRequestHeader('Content-Type', 'application/json');
          console.log(event);
          request.send(JSON.stringify(event));
        }
      </code>
    </pre>

    <h5>Call on HTML pages using:</h5>
    <code>&lt;a href="/example" onclick="wawametrics.report('EXAMPLE link clicked')"&gt;</code><br />
    or<br />
    <code>&lt;script&gt;wawametrics.report('EXAMPLE page loaded');&lt;/script&gt;</code>
  </p>
</container>